### PR TITLE
Add CI pipeline

### PR DESCRIPTION
**Pull request by ddugovic**
Continuous integration helps with troubleshooting problems which inevitably occur, and enforces code quality with a linter like flake8.

### CODE REVIEW

**Comment by Destaq** [comment]
Accepted!

**Comment by Destaq** [comment]
@ddugovic I am not very familiar with Workflows. I understand what it generally does, but will this yml file mean that whenever someone downloads my program, they will have the dependencies plotly and python-chess automatically installed?

Because from what I am reading this only activates upon `push` or `pull requests`. However I do not know much about CI pipelines. What exactly will the workflow do?

**Comment by ddugovic** [comment]
@Destaq Good questions:

* Downloading the source code will not automatically `pip install -r requirements.txt`.  This new `.yml` file only pertains to https://github.com/Destaq/chess_opening_graph/actions - things which GitHub hosts and automates for free (for open source projects) to encourage developers to continue using GitHub instead of other SCM sites (which might smoothly integrate with Travis CI or other CI providers).
* This pipeline will have GitHub automatically run `flake8` and `pytest` when commits or pull requests are made, at least as it is currently configured.  The "Actions" perspective will show whether those ran successfully or not, for example https://github.com/ddugovic/chess_opening_graph/actions shows the errors I had this morning on my `master` branch until I added a valid `requirements.txt` and a valid `*test.py` file which passed tests.

**Comment by Destaq** [comment]
@ddugovic Thanks for letting me know, that helps!

**Pull request merged**
